import { useState, useEffect, useCallback } from 'preact/hooks';
import { send, type AdReport, type RuntimeResponse } from '~/shared/messages';
import type { Settings } from '~/shared/settings';
import type { BlockStats } from '~/shared/types';

const REPO = 'Pkkls/kick-ad-blocker';

/** Send a message to the content script of the active Kick tab. */
async function sendToTab(msg: { type: string }): Promise<RuntimeResponse | null> {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  if (!tab?.id || !tab.url?.includes('kick.com')) return null;
  return new Promise((resolve) => {
    chrome.tabs.sendMessage(tab.id!, msg, (res: RuntimeResponse | undefined) => {
      if (chrome.runtime.lastError || !res) { resolve(null); return; }
      resolve(res);
    });
  });
}

/** Build a pre-filled GitHub issue URL from the ad report. */
function buildIssueUrl(report: AdReport): string {
  const title = encodeURIComponent(`Ad report: ${report.channel} (${report.timestamp.slice(0, 10)})`);
  const body = encodeURIComponent([
    '## Ad Report',
    '',
    `**Channel:** ${report.channel}`,
    `**URL:** ${report.url}`,
    `**Time:** ${report.timestamp}`,
    `**Extension:** v${report.extensionVersion}`,
    `**Player:** ${report.playerTech}`,
    '',
    '### Ad domains contacted',
    report.adDomains.length > 0
      ? report.adDomains.map((d) => `- \`${d}\``).join('\n')
      : '_None detected_',
    '',
    '### Ad elements in DOM',
    report.adElements.map((e) => `- \`${e}\``).join('\n'),
    '',
    '### Fingerprint diff vs baseline',
    report.fingerprint.map((f) => `- ${f}`).join('\n'),
    '',
    '### Description',
    '_Describe what you saw (pre-roll video, banner, overlay, etc.):_',
    '',
    '',
    '---',
    '_Auto-generated by Kick Ad Blocker_',
  ].join('\n'));
  return `https://github.com/${REPO}/issues/new?title=${title}&body=${body}&labels=ad-report`;
}

export function App() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [stats, setStats] = useState<BlockStats | null>(null);
  const [fpChanges, setFpChanges] = useState<string[]>([]);
  const [reporting, setReporting] = useState(false);
  const [onKick, setOnKick] = useState(false);

  const refresh = useCallback(async () => {
    const [sRes, stRes, fpRes] = await Promise.all([
      send({ type: 'settings.get' }),
      send({ type: 'stats.get' }),
      send({ type: 'fingerprint.get' }),
    ]);
    if (sRes.type === 'settings') setSettings(sRes.payload);
    if (stRes.type === 'stats') setStats(stRes.payload);
    if (fpRes.type === 'fingerprint') setFpChanges(fpRes.payload.changes);

    // Check if active tab is on Kick
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    setOnKick(!!tab?.url?.includes('kick.com'));
  }, []);

  useEffect(() => { refresh().catch(() => {}); }, [refresh]);

  const toggle = async () => {
    if (!settings) return;
    const res = await send({ type: 'settings.set', payload: { enabled: !settings.enabled } });
    if (res.type === 'settings') setSettings(res.payload);
  };

  const openOptions = () => {
    send({ type: 'open.options' }).catch(() => {});
  };

  const reportAd = async () => {
    setReporting(true);
    try {
      const res = await sendToTab({ type: 'report.capture' });
      if (res?.type === 'report') {
        const url = buildIssueUrl(res.payload);
        window.open(url, '_blank');
      } else {
        // Fallback: open blank issue
        window.open(`https://github.com/${REPO}/issues/new?labels=ad-report&title=Ad+report`, '_blank');
      }
    } catch {
      window.open(`https://github.com/${REPO}/issues/new?labels=ad-report&title=Ad+report`, '_blank');
    }
    setReporting(false);
  };

  const total = stats ? stats.networkBlocked + stats.domHidden : 0;

  return (
    <div class="p-4 space-y-3">
      {/* Header */}
      <div class="flex items-center justify-between">
        <div class="flex items-center gap-2">
          <svg class="w-6 h-6 text-kick-primary" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 15l-5-5 1.41-1.41L11 14.17l7.59-7.59L20 8l-9 9z" />
          </svg>
          <span class="font-bold text-lg">KAB</span>
          <span class="text-xs text-kick-muted">v{chrome.runtime.getManifest().version}</span>
        </div>
        <button
          onClick={toggle}
          class={`relative w-11 h-6 rounded-full transition-colors ${
            settings?.enabled ? 'bg-kick-primary' : 'bg-kick-border'
          }`}
        >
          <span
            class={`absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full transition-transform ${
              settings?.enabled ? 'translate-x-5' : ''
            }`}
          />
        </button>
      </div>

      {/* Stats */}
      {settings?.enabled && (
        <div class="bg-kick-surface rounded-lg p-4 text-center">
          <div class="text-3xl font-bold text-kick-primary">{total}</div>
          <div class="text-sm text-kick-muted mt-1">ads blocked today</div>
          {stats && (
            <div class="flex justify-center gap-4 mt-3 text-xs text-kick-muted">
              <span>{stats.networkBlocked} network</span>
              <span>{stats.domHidden} DOM</span>
            </div>
          )}
        </div>
      )}

      {/* Fingerprint alert */}
      {fpChanges.length > 0 && (
        <div class="bg-red-900/30 border border-red-500/40 rounded-lg p-3">
          <div class="text-xs font-bold text-red-400 mb-1">Ad-tech change detected</div>
          {fpChanges.map((c, i) => (
            <div key={i} class="text-xs text-red-300">{c}</div>
          ))}
        </div>
      )}

      {/* Disabled state */}
      {settings && !settings.enabled && (
        <div class="bg-kick-surface rounded-lg p-4 text-center text-kick-muted">
          Ad blocker disabled
        </div>
      )}

      {/* Report Ad button */}
      {settings?.enabled && onKick && (
        <button
          onClick={reportAd}
          disabled={reporting}
          class="w-full flex items-center justify-center gap-2 py-2 px-3 rounded-lg
                 bg-red-900/20 border border-red-500/30 text-red-400
                 hover:bg-red-900/40 hover:border-red-500/50
                 disabled:opacity-50 transition-colors text-sm"
        >
          <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
            <line x1="4" y1="22" x2="4" y2="15" />
          </svg>
          {reporting ? 'Capturing...' : 'Report an ad'}
        </button>
      )}

      {/* Footer */}
      <button
        onClick={openOptions}
        class="w-full text-center text-xs text-kick-muted hover:text-kick-text transition-colors py-1"
      >
        Options
      </button>
    </div>
  );
}
