/**
 * Injects a "Report Ad" flag button into the Kick page, next to the
 * viewer count (data-testid="viewer-count").
 *
 * The button captures a diagnostic snapshot and opens a pre-filled
 * GitHub issue so the report reaches the maintainer.
 */
import { captureFingerprint, diffFingerprint, BASELINE } from './fingerprint';
import { AD_SELECTOR_ALL } from './selectors';
import type { AdReport } from '~/shared/messages';
import { rootLogger } from '~/shared/logger';

const log = rootLogger.child('report-btn');
const REPO = 'Pkkls/kick-ad-blocker';
const BTN_ID = 'kab-report-btn';

/* ── Issue URL builder ── */

function buildIssueUrl(report: AdReport): string {
  const title = encodeURIComponent(
    `Ad report: ${report.channel} (${report.timestamp.slice(0, 10)})`,
  );
  const body = encodeURIComponent(
    [
      '## Ad Report',
      '',
      `**Channel:** ${report.channel}`,
      `**URL:** ${report.url}`,
      `**Time:** ${report.timestamp}`,
      `**Extension:** v${report.extensionVersion}`,
      `**Player:** ${report.playerTech}`,
      '',
      '### Ad domains contacted',
      report.adDomains.length > 0
        ? report.adDomains.map((d) => `- \`${d}\``).join('\n')
        : '_None detected_',
      '',
      '### Ad elements in DOM',
      report.adElements.map((e) => `- \`${e}\``).join('\n'),
      '',
      '### Fingerprint diff vs baseline',
      report.fingerprint.map((f) => `- ${f}`).join('\n'),
      '',
      '### What I saw',
      '_Describe the ad (pre-roll video, banner, overlay, etc.):_',
      '',
      '',
      '---',
      '_Auto-generated by Kick Ad Blocker_',
    ].join('\n'),
  );
  return `https://github.com/${REPO}/issues/new?title=${title}&body=${body}&labels=ad-report`;
}

/* ── Capture snapshot ── */

function capture(): AdReport {
  const fp = captureFingerprint();
  const changes = diffFingerprint(BASELINE, fp);

  const adEls: string[] = [];
  try {
    document.querySelectorAll(AD_SELECTOR_ALL).forEach((el) => {
      const tag = el.tagName;
      const id = el.id ? `#${el.id}` : '';
      const cls = el.className ? `.${String(el.className).split(' ')[0]}` : '';
      adEls.push(`${tag}${id}${cls}`);
    });
  } catch { /* ignore */ }

  const channel =
    location.pathname.replace(/^\//, '').split('/')[0] || 'unknown';

  return {
    url: location.href,
    channel,
    timestamp: new Date().toISOString(),
    fingerprint: changes.length > 0 ? changes : ['No changes from baseline'],
    adDomains: fp.adDomains,
    adElements: adEls.length > 0 ? adEls : ['None detected in DOM'],
    playerTech: fp.playerTech,
    extensionVersion: chrome.runtime.getManifest().version,
  };
}

/* ── Button creation ── */

function createButton(): HTMLButtonElement {
  const btn = document.createElement('button');
  btn.id = BTN_ID;
  btn.type = 'button';
  btn.title = 'Report an ad to Kick Ad Blocker';

  // Flag icon (SVG) + minimal styling to blend with Kick's UI
  btn.innerHTML = `
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none"
         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/>
      <line x1="4" y1="22" x2="4" y2="15"/>
    </svg>
  `;

  Object.assign(btn.style, {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'transparent',
    border: 'none',
    color: '#6b7888',
    cursor: 'pointer',
    padding: '4px',
    borderRadius: '4px',
    marginRight: '8px',
    transition: 'color 0.15s, background 0.15s',
    flexShrink: '0',
  } satisfies Partial<Record<keyof CSSStyleDeclaration, string>>);

  btn.addEventListener('mouseenter', () => {
    btn.style.color = '#ff4444';
    btn.style.background = 'rgba(255,68,68,0.1)';
  });
  btn.addEventListener('mouseleave', () => {
    btn.style.color = '#6b7888';
    btn.style.background = 'transparent';
  });

  btn.addEventListener('click', (e) => {
    e.preventDefault();
    e.stopPropagation();
    const report = capture();
    window.open(buildIssueUrl(report), '_blank');
  });

  return btn;
}

/* ── Injection logic ── */

/** Selector for the row containing viewer count + share + report buttons. */
const VIEWER_ROW_SELECTOR = '[data-testid="viewer-count"]';

function tryInject(): boolean {
  if (document.getElementById(BTN_ID)) return true;

  const viewerCount = document.querySelector(VIEWER_ROW_SELECTOR);
  if (!viewerCount) return false;

  // Parent is the flex row: div.flex.items-center.gap-2.self-end.py-0.5
  const row = viewerCount.parentElement;
  if (!row) return false;

  // Insert BEFORE the viewer count (left side)
  row.insertBefore(createButton(), viewerCount);
  log.debug('Report button injected');
  return true;
}

/**
 * Mount the report button. Polls until the viewer count element
 * appears (Kick loads it dynamically), then stops.
 */
export function mountReportButton(): void {
  if (tryInject()) return;

  // Kick is an SPA — viewer count may not exist yet. Observe until it appears.
  const observer = new MutationObserver(() => {
    if (tryInject()) {
      observer.disconnect();
    }
  });
  observer.observe(document.documentElement, { childList: true, subtree: true });

  // Safety timeout — stop observing after 60s
  setTimeout(() => observer.disconnect(), 60_000);
}

/** Remove the button (e.g. when extension is disabled). */
export function unmountReportButton(): void {
  document.getElementById(BTN_ID)?.remove();
}
